version: '3.4'
services:
  archipel.public.dappnode.eth:
    privileged: true
    build: ./build
    image: 'archipel.public.dappnode.eth:0.0.2'
    volumes:
      - 'data:/root/chain/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - '30333:30333'
      - '51820:51820'
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - WIREGUARD_PRIVATE_KEY=
      - WIREGUARD_ADDRESS=
      - WIREGUARD_LISTEN_PORT=51820
      - WIREGUARD_PEERS_PUB_ADDR=
      - WIREGUARD_PEERS_ALLOWED_IP=
      - WIREGUARD_PEERS_EXTERNAL_ADDR=
      - ARCHIPEL_NODE_ALIAS=
      - ARCHIPEL_KEY_SEED=
      - ARCHIPEL_CHAIN_ADDITIONAL_PARAMS=
      - ARCHIPEL_AUTHORITIES_SR25519_LIST=
      - ARCHIPEL_AUTHORITIES_ED25519_LIST=
      - SERVICE=polkadot
      - POLKADOT_NAME=
      - 'POLKADOT_IMAGE=parity/polkadot:latest'
      - POLKADOT_PREFIX=kusama-data-
      - POLKADOT_KEY_GRAN=
      - POLKADOT_KEY_BABE=
      - POLKADOT_KEY_IMON=
      - POLKADOT_KEY_PARA=
      - POLKADOT_KEY_AUDI=
    restart: always
volumes:
  data: {}
