version: '3.4'
services:
  archipel.public.dappnode.eth:
    build: ./build
    image: 'archipel.public.dappnode.eth:0.0.1'
    volumes:
      - 'config:/config/archipel'
      - /var/run/docker.sock:/var/run/docker.sock
      environment:
        - VALIDATOR_NETWORK=
        - VALIDATOR_NODE_ALIAS=
        - VALIDATOR_NODE_ADDRESS=
        # validator_node_keystore
        # path : /config/archipel/validator_node_keystore.json
        - VALIDATOR_NODE_KEYSTORE_PASSWORD=
        - ARCHIPEL_NODE_ALIAS=
        - ARCHIPEL_NODE_ADDRESS=
        # archipel_node_keystore
        # path : /config/archipel/archipel_node_keystore.json
        - ARCHIPEL_NODE_KEYSTORE_PASSWORD=
        - ARCHIPEL_BOOTNODES=
    restart: always
    volumes:
      config: {}