version: '3.4'
services:
  archipel.public.dappnode.eth:
    build: ./build
    image: 'archipel.public.dappnode.eth:0.0.2'
    volumes:
      - 'data:/root/chain/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'keys:/keys'
    ports:
      - '51820:51820/udp'
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - WIREGUARD_PRIVATE_KEY=
      - WIREGUARD_ADDRESS=
      - WIREGUARD_LISTEN_PORT=51820
      - WIREGUARD_PEERS_PUB_ADDR=
      - 'WIREGUARD_PEERS_ALLOWED_IP=10.0.1.1/32,10.0.1.2/32,10.0.1.3/32'
      - WIREGUARD_PEERS_EXTERNAL_ADDR=
      - ARCHIPEL_NODE_ALIAS=
      - ARCHIPEL_LISTEN_PORT=30334
      - ARCHIPEL_KEY_SEED=
      - ARCHIPEL_NODE_KEY_FILE=archipel_node_key_file
      - ARCHIPEL_CHAIN_ADDITIONAL_PARAMS=
      - ARCHIPEL_AUTHORITIES_SR25519_LIST=
      - ARCHIPEL_AUTHORITIES_ED25519_LIST=
      - SERVICE=polkadot
      - POLKADOT_NAME=
      - 'POLKADOT_IMAGE=parity/polkadot:latest'
      - POLKADOT_PREFIX=kusama-data-
      - POLKADOT_KEY_GRAN=
      - POLKADOT_KEY_BABE=
      - POLKADOT_KEY_IMON=
      - POLKADOT_KEY_PARA=
      - POLKADOT_KEY_AUDI=
      - POLKADOT_NODE_KEY_FILE=polkadot_node_key_file
      - POLKADOT_RESERVED_NODES=
      - POLKADOT_TELEMETRY_URL=
    restart: always
volumes:
  data: {}
  keys: {}
