version: '3.4'
services:
  archipel.public.dappnode.eth:
    build: ./build
    image: 'archipel.public.dappnode.eth:1.0.3'
    volumes:
      - 'data:/root/chain/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'service:/service'
      - 'config:/config'
    ports:
      - '51820:51820/udp'
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - CONFIG_FILE=true
      - CONFIG_FILE_PASSWORD=
      - NODE_ID=
      - WIREGUARD_PRIVATE_KEY=
      - WIREGUARD_ADDRESS=
      - WIREGUARD_LISTEN_PORT=
      - WIREGUARD_PEERS_PUB_ADDR=
      - WIREGUARD_PEERS_ALLOWED_IP=
      - WIREGUARD_PEERS_EXTERNAL_ADDR=
      - ARCHIPEL_NODE_ALIAS=
      - ARCHIPEL_LISTEN_PORT=
      - ARCHIPEL_KEY_SEED=
      - ARCHIPEL_NODE_KEY_FILE=
      - ARCHIPEL_RESERVED_PEERS=
      - ARCHIPEL_AUTHORITIES_SR25519_LIST=
      - ARCHIPEL_AUTHORITIES_ED25519_LIST=
      - ARCHIPEL_TELEMETRY_URL=
      - ARCHIPEL_SUSPEND_SERVICE=
      - SERVICE=polkadot
      - POLKADOT_NAME=
      - 'POLKADOT_IMAGE=parity/polkadot:latest'
      - POLKADOT_PREFIX=kusama-data-
      - POLKADOT_KEY_GRAN=
      - POLKADOT_KEY_BABE=
      - POLKADOT_KEY_IMON=
      - POLKADOT_KEY_PARA=
      - POLKADOT_KEY_AUDI=
      - POLKADOT_NODE_KEY_FILE=
      - POLKADOT_RESERVED_NODES=
      - POLKADOT_TELEMETRY_URL=
      - POLKADOT_LAUNCH_IN_VPN=true
      - POLKADOT_SIMULATE_SYNCH=false
      - POLKADOT_ADDITIONAL_OPTIONS=--db-cache 512 --rpc-methods=Unsafe
    restart: always
volumes:
  data: {}
  service: {}
  config: {}
